name: Rust CI

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install cargo audit
        run: cargo install cargo-audit

      - name: Build the project
        run: cargo build --verbose
        working-directory: ./src-tauri

      - name: Test the project
        run: cargo test
        working-directory: ./src-tauri

      - name: Run Clippy
        run: cargo clippy -- -D warnings
        working-directory: ./src-tauri

      - name: Run cargo audit
        run: cargo audit
        working-directory: ./src-tauri
