name: Rust CI

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install cargo audit
        run: cargo install cargo-audit

      - name: Build the project
        run: cargo build --verbose

      - name: Test the project
        run: cargo test

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Run cargo audit
        run: cargo audit
